version: '2'
services:
    jackett:
        image: linuxserver/jackett:90
        container_name: jackett
        restart: unless-stopped
        ports:
            - 9117:9117
        environment:
            - VIRTUAL_HOST=jackett.htpc
        volumes:
            - jackett_config:/config
            - /host_mnt/m/Torrents:/downloads
            - /host_mnt/m:/media
        networks:
            - htpc

    dashboard:
        image: chimpchimp/manage-this-node
        container_name: dashboard
        restart: unless-stopped
        ports:
            - 3000:3000
        environment:
            - VIRTUAL_HOST=dashboard.htpc
        volumes:
            - dashboard_config:/config
            - /host_mnt/m/Torrents:/downloads
            - /host_mnt/m:/media
        networks:
            - htpc

    nginx-proxy:
        image: jwilder/nginx-proxy
        container_name: nginx-proxy
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - VIRTUAL_PORT=80
            - VIRTUAL_PORT=443
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - nginx-proxy_config:/data:rw
            - nginx_certs:/etc/nginx/certs:ro
            - nginx_dhparam:/etc/nginx/dhparam:ro
        networks:
            - htpc

    emby:
        image: emby/embyserver
        container_name: emby
        restart: unless-stopped
        ports:
            - 8096:8096
        volumes:
            - emby_config:/config
            - /host_mnt/m:/media
        environment:
            - VIRTUAL_PORT=8096
            - VIRTUAL_HOST=emby.htpc
            - AUTO_UPDATES_ON=true
        networks:
            - htpc

    plex:
        image: linuxserver/plex
        container_name: plex
        ports:
            - 32401:32400
        volumes:
            - plex_config:/config
            - plex_transcode:/transcode
            - /host_mnt/m:/media
        restart: always
        environment:
            - VIRTUAL_PORT=32400
            - VIRTUAL_HOST=plex.htpc
            - VERSION=latest

    utorrent:
        image: ekho/utorrent
        container_name: utorrent
        volumes:
            - /host_mnt/m:/media
            - utorrent_config:/utorrent/settings
            - utorrent_data:/utorrent/data
        ports:
            - 8282:8080
            - 6881:6881
        restart: unless-stopped
        environment:
            - VIRTUAL_PORT=8282
            - VIRTUAL_HOST=utorrent.htpc
        networks:
            - htpc

    sonarr:
        image: 	linuxserver/sonarr
        container_name: sonarr
        volumes:
            - sonarr_config:/config
            - /host_mnt/m:/media
            - /host_mnt/m/Torrents:/downloads
        ports:
            - 8989:8989
        restart: always
        environment:
            - VIRTUAL_PORT=8989
            - VIRTUAL_HOST=sonarr.htpc
        networks:
            - htpc

    radarr:
        image: 	linuxserver/radarr
        container_name: radarr
        volumes:
            - radarr_config:/config
            - /host_mnt/m:/media
            - /host_mnt/m/Torrents:/downloads
            - /host_mnt/m/Movies:/movies
        ports:
            - 7878:7878
        restart: always
        environment:
            - VIRTUAL_PORT=7878
            - VIRTUAL_HOST=radarr.htpc
        networks:
            - htpc
            
    tautulli:
        image: 	linuxserver/tautulli
        container_name: tautulli
        volumes:
            - tautulli_config:/config
            - tautulli_logs:/logs
        ports:
            - 8181:8181
        restart: always
        environment:
            - VIRTUAL_PORT=8181
            - VIRTUAL_HOST=tautulli.htpc
        networks:
            - htpc
network:
    htpc:
            
